name: PR Validation
on: [pull_request]

jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.8"]
        poetry-version: [1.5.1]
    runs-on: ubuntu-latest
    env:
      RIOT_API_KEY: ${{ secrets.RIOT_API_KEY }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
      S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
      - name: Run code formatting
        run: ./.github/scripts/format.sh
      - name: Run tests
        run: ./.github/scripts/test.sh
