name: pytest
on: [push]

jobs:
  test:
    strategy:
      matrix:
        # TODO: Set up more python and poetry versions
        python-version: [3.9]
        poetry-version: [1.1.12]
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
        run: poetry install
      - name: Run test
        env:
          RIOT_API_KEY: ${{ secrets.RIOT_API_KEY }}
        run: poetry run pytest -v
